spring:
  datasource:
    url: jdbc:mysql://ambrosia-bistro.c5wsjpjjgbjj.eu-north-1.rds.amazonaws.com:3306/restaurant_management_system?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    generate-ddl: true